### ISSUE TITLE
Improving plots recipes

### ISSUE THREAD

**Issue by ChrisRackauckas** [ChrisRackauckas/DifferentialEquations.jl#4]
The plot function for animations can be improved. Right now it's a little (or a lot) hacky. The core is that it plots:

```
push!(ps,plotfunc(sol.femMesh.node[:,1],sol.femMesh.node[:,2],sol.timeSeries[i][j]))
```

at each step where this is in (x,y,z[i]) form where there are i different plots made at each step j. Plotfunc is the chosen plotting function, which is only used because this isn't a recipe implementation. 

```
atomLoaded ? Main.Atom.progress(j/length(sol.timeSeries[1])) : nothing #Use Atom's progressbar if loaded
```

adds an Atom progressbar if the user is using Atom, which I find necessary convenience for long animations. 

Using a recipe will likely also have a way to choose the backend? Right now it's set to PyPlot, but it should be able to switch to something like GR when it's surface plots, but should also handle trisurf plots (when those are implemented in Plots).

**Comment by tbreloff** [comment]
So is there some reason why this pattern wouldn't work?

```julia
@gif for j=1:num_steps
    #  TODO update the atom progress
    timeseries = [ts[j] for ts in sol.timeSeries]
    plotfunc(sol.femMesh.node[:,1], sol.femMesh.node[:,2], timeseries)
end
```

And then you'd create either/both of "type recipes" and "user recipes" depending on what you need.

**Comment by tbreloff** [comment]
I've never actually tried switching backends mid-recipe.  It might work???

**Comment by ChrisRackauckas** [comment]
I am still not quite sure how to make the `@gif` command be in a recipe. Do you just put it at the bottom, and so the recipe is returning an animation instead of a plot?

I was just following your example with the backend thing. The `reuse=true` is necessary, and if that's the case it's nice to have it in the animation call, but I am wondering if it could grab the current backend and add that, and then after the animation is made turn it back to the way it was?

**Comment by ChrisRackauckas** [comment]
FYI the tests fail after removing the checkout calls from the tests. Has the METADATA just not updated or something? It fails because the keyword `plottrue` that I defined for some recipes is not found, which is an issue only when called on an older version of Plots.

**Comment by tbreloff** [comment]
What are the types on these:

```
sol.femMesh.node[:,1],sol.femMesh.node[:,2],sol.timeSeries[i][j]
```

> I am still not quite sure how to make the @gif command be in a recipe. Do you just put it at the bottom, and so the recipe is returning an animation instead of a plot?

The recipes would be called from within the `plotfunc` call.  You wouldn't add any animation logic to a recipe.

You made me realize an important point (that I was already pondering but chose to ignore), that recipes aren't used when pushing/updating data.  I think it would make sense to process "type recipes" inside `push!`/`setindex!` methods, but other recipes would be tricky to get right generically.  If you're pushing data into a histogram recipe, for example, you'd want to update the bins accordingly, which involved changing the original data and then re-processing the recipe.  This is certainly do-able, but might be a "0.8 feature".

**Comment by tbreloff** [comment]
Though looking at your animation function, it seems like you're just rebuilding a plot for each frame, so things would work fine.
