### ISSUE TITLE
issue with ODE backend

### ISSUE THREAD

**Issue by rveltz** [ChrisRackauckas/DifferentialEquations.jl#42]
Hi

Trying [https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/examples/Calling%20External%20Solvers%20-%20ODEjl%20and%20ODEInterface.ipynb](url) to call ode45, I get the following error:

`sol =solve(prob::ODEProblem,tspan,Δt=Δt,alg=:ode45)
[DifferentialEquations.jl] Initializing backend: ODEJL
ERROR: UndefVarError: ExplicitODE not defined
 in #solve#461(::Array{Any,1}, ::Function, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at /Users/rveltz/.julia/v0.5/DifferentialEquations/src/ode/ode_solve.jl:195
 in (::DifferentialEquations.#kw##solve)(::Array{Any,1}, ::DifferentialEquations.#solve, ::DifferentialEquations.ODEProblem{Array{Float64,1},Float64}, ::Array{Int64,1}) at ./<missing>:0`

Do you have any idea what is wrong?

`versioninfo()
Julia Version 0.5.0-rc0+0
Commit 0030eec* (2016-07-26 20:22 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
`

Pkg.status("DifferentialEquations")
 - DifferentialEquations         0.2.1+             master

**Comment by ChrisRackauckas** [comment]
As noted in the docs, [you have to be on the JuliaODE repository's version of ODE.jl](http://chrisrackauckas.github.io/DifferentialEquations.jl/latest/man/conditional_dependencies/), at least until pwl's PR goes through. It saying `ExplicitODE not defined` is telling me you're on `JuliaLang/ODE.jl` which doesn't have that part defined.

BTW, you might want to [check out the benchmarks I just ran](https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/benchmarks/Runge-Kutta%20Benchmarks%20on%20Linear%20ODEs.ipynb) for [nonstiff methods](https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/benchmarks/Three%20Body%20Benchmarks.ipynb). ODE.jl's methods don't fair too well. For pure speed go with ODEInterface algs. For speed + low error go with the DifferentialEquations.jl algs. But I haven't found a case where `ode45` performs well...

**Comment by rveltz** [comment]
Thank you!

**Comment by ChrisRackauckas** [comment]
No problem. Hopefully the standard branch will be able to be used soon.
