### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by matthieugomez** [ChrisRackauckas/DifferentialEquations.jl#43]
No version of the package loads correctly.
`Using` the package after `Pkg.install()` returns an error with BezierCurve (https://groups.google.com/forum/#!topic/julia-users/JpznWG2isxA)
`Using` the package after `Pkg.update()` returns the error
```julia
LoadError: LoadError: ArgumentError: argument is not a generic function
 in methods at reflection.jl:180
```

**Comment by ChrisRackauckas** [comment]
Use `Pkg.free()`. That error is something on master that's not compatible with v0.4. This is just because some tests now use anonymous functions but one part of the FEM suite is looking for number of methods.

(I think it's best to wait until tonight. The latest docs are all updated with these huge changes, but there are a few last bugs I need to fix to get it working on older versions of Julia. I need to iron those out and then I'll be releasing a new version. Note that you can just use the last tagged version, but there's been a pretty decent API change to match the ODE packages (and the last version doesn't have Sundials)... I'll post here when it should all be together.)

**Comment by ChrisRackauckas** [comment]
FYI, the problem is this if you know a solution: http://stackoverflow.com/questions/39150133/number-of-parameters-for-an-anonymous-function-in-v0-4. If the solution isn't bad I can just add that in there and it should work on v0.4 again. But everything should be working on v0.5 (I'm running it right now).

**Comment by ChrisRackauckas** [comment]
Master should work now. I'll know for sure when tests go through, but given some quick tests on v0.4 of my laptop it looks like it works.

**Comment by matthieugomez** [comment]
Due to the BezierCurbe issue, I think I still need Julia 0.5 no?

**Comment by ChrisRackauckas** [comment]
I don't know what you're talking about with the BezierCurve issue. DifferentialEquations doesn't depend on it, and actually it doesn't look like any package depends on it:

```julia
Pkg.dependents("BezierCurve")
```

And Travis/Appvoyer are able to build/test DifferentialEquations on v0.4 (when the numparameter test isn't failing, but that's a small oddity). And they don't install BezierCurve when doing so.

If you Pkg.rm("BezierCurve"), what happens?

**Comment by matthieugomez** [comment]
Sorry I was not more clear. I obtain this error message with the last tagged version or the current master version
```
ERROR: LoadError: LoadError: syntax: invalid method name "bc::BezierCurve"
 in include at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
while loading /Users/Matthieu/.julia/v0.4/Plots/src/components.jl, in expression starting on line 486
while loading /Users/Matthieu/.julia/v0.4/Plots/src/Plots.jl, in expression starting on line 130
ERROR: LoadError: Failed to precompile Plots to /Users/Matthieu/.julia/lib/v0.4/Plots.ji
 in error at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in compilecache at loading.jl:400
 in require at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
while loading /Users/Matthieu/.julia/v0.4/DifferentialEquations/src/DifferentialEquations.jl, in expression starting on line 5
ERROR: Failed to precompile DifferentialEquations to /Users/Matthieu/.julia/lib/v0.4/DifferentialEquations.ji
 in error at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in compilecache at loading.jl:400
 in require at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
```

(similarly to https://groups.google.com/forum/#!topic/julia-users/JpznWG2isxA)

**Comment by ChrisRackauckas** [comment]
That's not DifferentialEquations, that's Plots.jl whose pre-compilation is failing. @tbreloff do you know what this is?

**Comment by tbreloff** [comment]
Is BezierCurve a package? Because it's a type in Plots. Maybe it thinks the
function is declaring a module instead of a type because of the name clash?
I don't know anything about the package.

I could probably stop exporting the type from Plots though...

**Comment by ChrisRackauckas** [comment]
I think it must be a method on that type then. I assumed from what he was saying that it was a package that had something to do with Plots. I don't have a BezierCurve type so it wouldn't be conflicting with anything from me, but it's hard to tell with  dependencies.

**Comment by matthieugomez** [comment]
To be clear works on Julia 0.5. The issue is with 0.4

**Comment by tbreloff** [comment]
Wait. I think this is a 0.4 vs 0.5 incompatibility. Maybe he checked out a
recent version of Plots (which is now 0.5-only)??

**Comment by matthieugomez** [comment]
Ok I got it. So`DifferentialEquations` on Julia 0.4 requires version of Plots <= 0.8.
```julia
Pkg.pin("Plots", v"0.8.2")
```
Thanks a lot!

**Comment by tbreloff** [comment]
Does DE require Plots at all? I thought you were using recipes.

**Comment by ChrisRackauckas** [comment]
I have a function for animations, so Plots needs to be a dependency (unless something changed since the last time we discussed this).

**Comment by ChrisRackauckas** [comment]
I think it's okay though: the integration with Plots is pretty strong. I don't think many people would solve differential equations without making a plot. However, if there was a way to have the animations be PlotAnimations or something (and siphon off the docs / extra issues to its own repo), I'd be for that idea.

**Comment by tbreloff** [comment]
> Pkg.pin("Plots", v"0.8.2")

I just checked the requires file for DifferentialEquations and it seems fine.  Plots 0.8.2 should have been installed.  I think Plots was checked out... I don't think it should need to be pinned.  Try `Pkg.free("Plots")` and see if you still see the problem?

> I have a function for animations, so Plots needs to be a dependency

Ok I haven't come up with a good solution for this (well to be more correct, I haven't even tried ;)
